# Generated by Django 5.2.6 on 2025-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
